export const OPEN_BACKDROP = 'OPEN_BACKDROP'
export const CLOSE_BACKDROP = 'CLOSE_BACKDROP'


export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'
export const SHOW_SIDE_BACKDROP = 'SHOW_SIDE_BACKDROP'
export const CLOSE_SIDE_BACKDROP = 'CLOSE_SIDE_BACKDROP'


export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const TOGGLE_CART = 'TOGGLE_CART'
export const CLOSE_CART = 'CLOSE_CART'
export const OPEN_LOGIN = 'OPEN_LOGIN'
export const CLOSE_LOGIN = 'CLOSE_LOGIN'
export const FILTER_ITEMS = 'FILTER_ITEMS'



export const BUY_OPTIONS = 'BUY_OPTIONS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const OPEN_BUY_OPTIONS = 'OPEN_BUY_OPTIONS'
export const CLOSE_BUY_OPTIONS = 'CLOSE_BUY_OPTIONS'

export const FILTER_CATEGORIES = 'FILTER_CATEGORIES'
export const GET_ITEM_VALUE = 'GET_ITEM_VALUE'
export const GET_SIZE_VALUE = 'GET_SIZE_VALUE'
export const SET_SHOP_ITEMS = 'SET_SHOP_ITEMS'
export const RESET_SHOP = 'RESET_SHOP'
export const UPDATE_SHOP_PURCHASABLE = 'UPDATE_SHOP_PURCHASABLE'

export const UPDATE_SHOP_ITEMS = 'UPDATE_SHOP_ITEMS'
export const RESET_SHOP_ITEM = 'RESET_SHOP_ITEM'
export const SEARCH_SHOP_ITEMS = 'SEARCH_SHOP_ITEMS'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_CART_COUNT = 'UPDATE_CART_COUNT'

export const GO_TO_CHECKOUT = 'GO_TO_CHECKOUT '
export const CHECKOUT_CLICKED = 'CHECKOUT_CLICKED '
export const CHECKOUT_NOT_CLICKED = 'CHECKOUT_NOT_CLICKED '

export const IS_AUTH = 'IS_AUTH'
export const LOGIN_AUTH_FAILED = 'REGISTER_AUTH_FAILED'
export const REGISTER_AUTH_FAILED = 'REGISTER_AUTH_FAILED'
export const START_AUTH = 'START_AUTH'
export const REMOVE_AUTH = 'REMOVE_AUTH'
export const CHECK_AUTH = 'CHECK_AUTH'

export const USER_RETRIEVED = 'USER_RETRIEVED'


export const CLEAR_CART = "CLEAR_CART";



export const OPEN_PAYMENT = 'OPEN_PAYMENT'
export const CLOSE_PAYMENT = 'CLOSE_PAYMENT'
export const GETTING_ORDER = 'GETTING_ORDER'
export const ORDER_RETREIVED = 'ORDER_RETREIVED'


export const ORDER_START = 'ORDER_START'
export const ORDER_SUCCESS = 'ORDER_SUCCESS'
export const ORDER_FAILED = 'ORDER_FAILED'



export const SORT = 'SORT_ITEMS'

export const START_VERIFICATION = 'START_VERIFICATION'

