export const TOGGLE_BACKDROP = 'TOGGLE_BACKDROP'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const TOGGLE_CART = 'TOGGLE_CART'
export const CLOSE_CART = 'CLOSE_CART'
export const OPEN_LOGIN = 'OPEN_LOGIN'
export const CLOSE_LOGIN = 'CLOSE_LOGIN'
export const FILTER_ITEMS = 'FILTER_ITEMS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const FILTER_CATEGORIES = 'FILTER_CATEGORIES'
export const GET_ITEM_VALUE = 'GET_ITEM_VALUE'
export const SET_SHOP_ITEMS = 'SET_SHOP_ITEMS'
export const REMOVE_SHOP_ITEM = 'REMOVE_SHOP_ITEM'
export const UPDATE_SHOP_PURCHASABLE = 'UPDATE_SHOP_PURCHASABLE'

export const UPDATE_SHOP_ITEMS = 'UPDATE_SHOP_ITEMS'
export const RESET_SHOP_ITEM = 'RESET_SHOP_ITEM'
export const SEARCH_SHOP_ITEMS = 'SEARCH_SHOP_ITEMS'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_CART_COUNT = 'UPDATE_CART_COUNT'

export const GO_TO_CHECKOUT = 'GO_TO_CHECKOUT '
export const CHECKOUT_CLICKED = 'CHECKOUT_CLICKED '
export const CHECKOUT_NOT_CLICKED = 'CHECKOUT_NOT_CLICKED '

export const IS_AUTH = 'IS_AUTH'
export const REMOVE_AUTH = 'REMOVE_AUTH'

export const OPEN_PAYMENT = 'OPEN_PAYMENT'
export const CLOSE_PAYMENT = 'CLOSE_PAYMENT'

export const SORT = 'SORT_ITEMS'
